### PR TITLE
suite: make suite.TestingT satisfy mock.TestingT

### PR DESCRIPTION
**Pull request by hugelgupf**
...by adding Logf method.

### CODE REVIEW

**Comment by hugelgupf** [comment]
> Thanks, clearly something we forgot :)
> 
> Is it possible to add a unit test for this? i.e. some kind of test that asserts that the `suite.TestingT` interface can satisfy the `mock.TestingT` interface?

I would prefer you do that -- I'm not super familiar with testify; I'm just trying to fix a dependency of a dependency for me

**Comment by boyan-soubachov** [comment]
> > Thanks, clearly something we forgot :)
> > Is it possible to add a unit test for this? i.e. some kind of test that asserts that the `suite.TestingT` interface can satisfy the `mock.TestingT` interface?
> 
> I would prefer you do that -- I'm not super familiar with testify; I'm just trying to fix a dependency of a dependency for me

Fair enough, I'll add the test in parallel to this :)

**Comment by hugelgupf** [comment]
Feel free to push it to the branch in this PR and merge it all at once

**Comment by hugelgupf** [comment]
Thanks!

**Pull request merged**
