### PR TITLE
Added NotFileExists and NotDirExists to assertions

### PR DESCRIPTION
**Pull request by elliotforbes**

### CODE REVIEW

**Comment by asv1** [comment]
Why it not merged yet?

**Comment by elliotforbes** [comment]
There seems to be an issue with gofmt on 1.8 and 1.9 builds. I can't seem to find what the issue is, can one of the moment - @georgelesica-wf  can you take a look when you get a moment?

**Comment by georgelesica-wf** [comment]
Looking...

**Comment by georgelesica-wf** [comment]
Would you mind cherry-picking this into your branch and seeing if that makes it pass? https://github.com/stretchr/testify/pull/760

**Comment by georgelesica-wf** [comment]
I think you may be able to drop the changes I had asked you to cherry-pick. Sorry, still getting the codegen sorted out.

**Comment by georgelesica-wf** [comment]
Also, could you update the description at the top to include a high-level summary of your changes?

**Pull request closed without merging**
