### PR TITLE
Add parameter to stop Diff() causing data races

### PR DESCRIPTION
**Pull request by jacobgreenleaf**
If one of the arguments to a mocked object is concurrently written to during a test, then there can be a data race. When the mock calls `Called()` which calls `findExpectedCall()` which calls `Diff()` between the expected and actual arguments, it computes a stringified version of the actual argument. This causes a read, which can conflict with the write that is done by the system under test. This change only computes the stringified version if necessary, so that this read is avoided.

### CODE REVIEW

**Comment by ernesto-jimenez** [comment]
@jacobgreenleaf sorry it took so long to get to your PR. I've been crazy busy.

Can you submit a failing test that is fixed by these changes to see what races were found and confirm all were fixed?

Thanks!
Ernesto

**Comment by jacobgreenleaf** [comment]
@ernesto-jimenez Excellent advice. I have added a failing test case for this! Thanks.

**Comment by jacobgreenleaf** [comment]
For reference, here is what it looks like when I cherry pick just the test and run it:

    $ go test -race -v -run "Test_Mock_T312" ./mock
    === RUN   Test_Mock_T312
    ==================
    WARNING: DATA RACE
    Read by goroutine 6:
      reflect.maplen()
          /usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:981 +0x0
      reflect.Value.MapKeys()
          /usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:1066 +0x10f
      fmt.(*pp).printReflectValue()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:893 +0x2eb1
      fmt.(*pp).printValue()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:848 +0x551
      fmt.(*pp).printReflectValue()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:945 +0x2839
      fmt.(*pp).printValue()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:848 +0x551
      fmt.(*pp).printReflectValue()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:990 +0x181d
      fmt.(*pp).printArg()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:810 +0x652
      fmt.(*pp).doPrintf()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:1219 +0x2a52
      fmt.Sprintf()
          /usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:203 +0x7c
      github.com/stretchr/testify/mock.Arguments.Diff()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock.go:592 +0x1b01
      github.com/stretchr/testify/mock.(*Mock).findExpectedCall()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock.go:220 +0x22a
      github.com/stretchr/testify/mock.(*Mock).Called()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock.go:289 +0x2b8
      github.com/stretchr/testify/mock.(*TestExampleImplementation).TheExampleMethodVariadicInterface()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock_test.go:55 +0x143
      github.com/stretchr/testify/mock.Test_Mock_T312()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock_test.go:1150 +0x335
      testing.tRunner()
          /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0xdc

    Previous write by goroutine 7:
      runtime.mapassign1()
          /usr/local/Cellar/go/1.5.1/libexec/src/runtime/hashmap.go:411 +0x0
      github.com/stretchr/testify/mock.Test_Mock_T312.func1()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock_test.go:1146 +0x60

    Goroutine 6 (running) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:561 +0xaa3
      testing.(*M).Run()
          /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:494 +0xe4
      main.main()
          github.com/stretchr/testify/mock/_test/_testmain.go:178 +0x20f

    Goroutine 7 (finished) created at:
      github.com/stretchr/testify/mock.Test_Mock_T312()
          /Users/jacobgreenleaf/gocode/src/github.com/stretchr/testify/mock/mock_test.go:1148 +0x27d
      testing.tRunner()
          /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0xdc
    ==================
    --- PASS: Test_Mock_T312 (0.00s)
    PASS
    Found 1 data race(s)
    exit status 66
    FAIL    github.com/stretchr/testify/mock        1.016s

**Comment by ernesto-jimenez** [comment]
Thanks @jacobgreenleaf,

I just checked out the changes and it looks like this would only hide the change.

When I add `mockedService.AssertExpectations(t)` to the test the race surfaces again.

```
==================
WARNING: DATA RACE
Read at 0x00c4202eaf90 by goroutine 70:
  reflect.maplen()
      /usr/local/Cellar/go/1.7/libexec/src/runtime/hashmap.go:1044 +0x0
  reflect.Value.MapKeys()
      /usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:1072 +0x427
  fmt.(*pp).printValue()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:727 +0x164b
  fmt.(*pp).printValue()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:777 +0x256e
  fmt.(*pp).printValue()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:824 +0xeb1
  fmt.(*pp).printArg()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:668 +0x1a3
  fmt.(*pp).doPrintf()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:985 +0x1d2a
  fmt.Sprintf()
      /usr/local/Cellar/go/1.7/libexec/src/fmt/print.go:196 +0x77
  github.com/stretchr/testify/mock.Arguments.diff()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock.go:608 +0xaba
  github.com/stretchr/testify/mock.Arguments.Diff()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock.go:546 +0x82
  github.com/stretchr/testify/mock.(*Mock).methodWasCalled()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock.go:424 +0x1c8
  github.com/stretchr/testify/mock.(*Mock).AssertExpectations()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock.go:366 +0x11b
  github.com/stretchr/testify/mock.Test_Mock_T312()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock_test.go:1146 +0x282
  testing.tRunner()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:610 +0xc9

Previous write at 0x00c4202eaf90 by goroutine 71:
  runtime.mapassign1()
      /usr/local/Cellar/go/1.7/libexec/src/runtime/hashmap.go:442 +0x0
  github.com/stretchr/testify/mock.Test_Mock_T312.func1()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock_test.go:1142 +0x6a

Goroutine 70 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:743 +0x12f
  main.main()
      github.com/stretchr/testify/mock/_test/_testmain.go:178 +0x1b8

Goroutine 71 (finished) created at:
  github.com/stretchr/testify/mock.Test_Mock_T312()
      /Users/ernesto/Projects/go/src/github.com/stretchr/testify/mock/mock_test.go:1143 +0x1ee
  testing.tRunner()
      /usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:610 +0xc9
==================
PASS
Found 1 data race(s)
FAIL	github.com/stretchr/testify/mock	1.054s
```

We do have to use `sync.Mutex` in some parts of the mock package, but this is trickier because the write has nothing to do with mock, so it is not something we can protect with a mutex.

**Comment by jacobgreenleaf** [comment]
You are right. There is not a great way to do this in Go; there should be a way to inform the race detector that the calling goroutine should be ignored for race detection purposes. Closing.

**Comment by ernesto-jimenez** [comment]
Jacob, thanks for giving it a go! :)

**Pull request closed without merging**
