### PR TITLE
optimize isBetterMatchThan

### PR DESCRIPTION
**Pull request by bestgopher**

### CODE REVIEW

**Comment by arsham** [comment]
But, why?

**Comment by bestgopher** [comment]
> But, why?
I don't like to judge the Boolean of the return value of an expression, and then return a Boolean. We can directly return the value of this expression. This is just my personal habit. 

For example, in this function, These two sentences
```
if c.call.Repeatability > 0 && other.call.Repeatability <= 0 {	
		return true	
	}
return false
```
can be written like this
```
return c.call.Repeatability > 0 && other.call.Repeatability <= 0
```

Of course, if you don’t approve, I can also close this pr.

**Comment by arsham** [comment]
I'm not a maintainer in this repo therefore it's not my call.

Just to quote [Rob Pike](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=14m35s)
```
Clear is better than clever.
```

**Comment by bestgopher** [comment]
> I'm not a maintainer in this repo therefore it's not my call.
> 
> Just to quote [Rob Pike](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=14m35s)
> 
> ```
> Clear is better than clever.
> ```

Thank you for your suggestions and comments. @arsham

**Pull request closed without merging**
