### PR TITLE
chore(gomod): use stable yaml version

### PR DESCRIPTION
**Pull request by georgettica**
this might solve all of the erros of go-get

partially fixes https://github.com/stretchr/testify/issues/757

### CODE REVIEW

**Comment by SVilgelm** [comment]
I'm just curious what issues do you have with go get so you want to use v2 instead of v3?

**Comment by georgettica** [comment]
I am going through security suits, and one of the things is using tagged versions and not the `go get *@main`
Also, this makes updating more confusing

**Comment by georgettica** [comment]
The tests I was running were on github.com/ossf/scorecard

**Comment by SVilgelm** [comment]
hmm, what is wrong with `go get *@main`, why is the `go get *@vN` considered more secure? It only depends how a maintainer releases the projects. There are a lot of packages that have no tags or branches (except main) at all, but it does not make them less secure.

The problem here is that the maintainer of go-yaml does not follow best practices in how to release the libs. Actually he didn't release any versions for v3, also v2 branch has no updates since Nov 17, 2020.

Is there any ope CVE against yaml.v3, that are not fixed in v3.0.0-20200313102051-9f266ea9e77c?

**Comment by SVilgelm** [comment]
And v2 branch has two open issues: https://osv.dev/list?q=yaml&affected_only=true&page=1&ecosystem=Go
and those issues are fixed in v3 and cannot be fixed in v2 with our breaking backwards compatibility

**Pull request closed without merging**
