### PR TITLE
assert.InDeltaSlice: new assertion

### PR DESCRIPTION
**Pull request by lazywei**
As mentioned in #133, I'm wondering if I could add this feature.
Please let me know if there is any concern.
Thanks!

### CODE REVIEW

**Comment by ccustine** [comment]
:+1:  This would be a nice addition.

**Comment by tylerb** [comment]
@lazywei please write a test for this new function.

**Comment by DAddYE** [comment]
Please add a test.

**Comment by lazywei** [comment]
Sorry for delay. I just add the testing.

**Comment by DAddYE** [comment]
Thanks

**Pull request merged**
