### PR TITLE
align error message

### PR DESCRIPTION
**Pull request by Wing924**
Align error message

AS IS:
```
	Error:      	Not equal: 
	            	expected: "foo01"
	            	actual: "foo02"
```

TO BE:
```
	Error:      	Not equal: 
	            	expected: "foo01"
	            	actual:   "foo02"
```

### CODE REVIEW

**Comment by nicolaiskogheim** [comment]
Is this the same as #485?

**Comment by Wing924** [comment]
@nicolaiskogheim 
Yes, it looks the same.

**Comment by Oppodelldog** [comment]
Yes, it is.

**Comment by ernesto-jimenez** [comment]
@Wing924 @nicolaiskogheim merged https://github.com/stretchr/testify/pull/485

**Pull request closed without merging**
