### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by davidporos92**
## Summary

Added the missing closing parentheses to some docs.

## Changes

Via fixing this typo, the generated code have also added the formatting parameters to the docs.

## Motivation

To fix the docs ;)

### CODE REVIEW

**Comment by davidporos92** [comment]
The tests are running fine on my machine 🤔 
Do you have any suggestions?

**Comment by davidporos92** [comment]
Sorry, Closed by mistake!

**Review by self-maurya — APPROVED** [review]

**Review by self-maurya — APPROVED** [review]

**Review by boyan-soubachov — CHANGES_REQUESTED** [review]
These docstrings are programmatically generated. Do you mind having a look at the `_codegen` folder. There is most likely a bug in the code there :)

I think it would be better to fix the issue at the source since next time a commit is made, these fixes in their current form will be undone since the `_codegen` logic will be re-run.

**Comment by boyan-soubachov** [comment]
Closing PR due to inactivity, happy to relook again if you'd like to carry on with some work on this :)

**Pull request closed without merging**
