### PR TITLE
assert.EqualExportedValues: fix handling of arrays

### LINKED ISSUE #1404: EqualExportedValues panic when struct contains array
Hi

```golang
package main

import (
	"github.com/stretchr/testify/assert"
)

type Foo struct {
	Array [2]int
}

func main() {
	a := Foo{[2]int{1, 2}}
	b := Foo{[2]int{2, 1}}
	assert.EqualExportedValues(nil, a, b)
}
```

Will panic with "panic: reflect.MakeSlice of non-slice type"

Reason is there in assertion.go:113 :
```golang
case reflect.Array, reflect.Slice:
	result := reflect.MakeSlice(expectedType, expectedValue.Len(), expectedValue.Len())
```

reflect.MakeSlice only work with slice, not with Array. Fix could be follow:

```golang
case reflect.Array, reflect.Slice:
	result := reflect.New(expectedType).Elem()
	if expectedKind == reflect.Slice {
		result = reflect.MakeSlice(expectedType, expectedValue.Len(), expectedValue.Len())
	}
```

Or even carry reflect.Array to different switch case

### PR DESCRIPTION
**Pull request by zrbecker**
## Summary

In EqualExportedValues, testify treats an Array as a Slice, however, the reflect library throws an error if the type passed to `reflect.MakeSlice` is not a Slice kind. This issue was identified in #1404

The result is a [very simple test](https://go.dev/play/p/Rxk9Z1Cvsx9) such as 
```go
func TestEqualExportedValuesWithArray(t *testing.T) {
	type S struct{ Values [2]int }
	require.EqualExportedValues(t, S{Values: [2]int{1, 2}}, S{Values: [2]int{1, 2}})
}
```

results in a panic

```
panic: reflect.MakeSlice of non-slice type
```

This PR adjusts the offending switch statement in `copyExportedFields` to handle arrays separately, and construct the array using `reflect.New(reflect.ArrayOf(len, type)).Elem()` instead of `reflect.MakeSlice`.

## Changes

- Changed `copyExportedFields` (used by `EqualExportedValues`) to handle Array type separately from Slices as they must be constructed differently.

- Added a test case to `TestEqualExportedValues` to verify an array object can be set on object passed to `EqualExportedValues`.

## Motivation

A user was unable to use `EqualExportedValues` if they had an exported array type nested somewhere in their struct.

A test like this will now pass
```go
func TestEqualExportedValuesWithArray(t *testing.T) {
	type S struct{ Values [2]int }
	require.EqualExportedValues(t, S{Values: [2]int{1, 2}}, S{Values: [2]int{1, 2}})
}
```

## Related issues

Closes #1404

### CODE REVIEW

**Comment by zrbecker** [comment]
@HaraldNordgren Looks like this was introduce in #1379, I saw this along with the issue you are addressing in #1384.

**Comment by HaraldNordgren** [comment]
Awesome!

**Review by HaraldNordgren — CHANGES_REQUESTED** [review]
(See my comment above)

**Comment by HaraldNordgren** [comment]
@dolmen @boyan-soubachov Can you take a look at this? It's a good change that should be merged to unbreak the code.

**Review by dolmen — CHANGES_REQUESTED** [review]
The only difference between the reflect.Array and reflect.Slice blocks are how `result` is allocated.
Please refactor to keep a single switch block and just branch with an if for the construction of `result`.

**Comment by zrbecker** [comment]
@dolmen I moved the two cases into a single switch statement to reduce code duplication as requested.

**Review by dolmen — APPROVED** [review]
Thank you!

**Pull request merged**
