### PR TITLE
Elminating backwards and improving consistentency across APIs

### PR DESCRIPTION
**Pull request by Fiery**
There was backwards API as discussed before, e.g. #146 , and here is the final fix to those mentioned.

### CODE REVIEW

**Comment by DAddYE** [comment]
Will probably break some compatibility but can't wait to have this merged :+1:

**Comment by Fiery** [comment]
Was wondering why `go test` didn't cover all cases and then realized that I need to test sub packages separately...

**Comment by ernesto-jimenez** [comment]
@Flery, @DAddYE 

Do you have any knowledge about other big packages introducing breaking changes like these without having to rely on versioning through versioning in package URLs?

The core team used to use [gofix](https://blog.golang.org/introducing-gofix) when making breaking changes to the stdlib pre Go 1.0.

This kind of change could easily be fixed automatically in the code, but there would need to be a way to let people know they need to run the gofix/gofix-like tool once they have upgraded the package, rather than just having code not compiling.

**Comment by Fiery** [comment]
@ernesto-jimenez you're right, may be we can consider create a migrating script using gofix and highlight it at very top of README.md to make it noticeable enough? [Kubernetes](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/README.md) does a good job to notify users about document discrepancies between different releases.

**Comment by jzila** [comment]
This is great; I was getting frustrated with the inconsistent ordering of expected vs actual parameters, I hope this PR makes it! :+1:

**Comment by ernesto-jimenez** [comment]
@Fiery sorry it took some time to reply, I've been crazy busy the past few weeks.

I've been thinking about this and my concern would be: how will developers know they have a script they can run to fix their code?

In most cases people would just fetch the new version and their tests will break. Specially in the cases were they will not even get a compilation error because we are swapping arguments that take an empty interface.

**Comment by oryband** [comment]
Any effort and getting this merged?

Perhaps you can just bump the version to v2 and be done with it?

**Comment by xordspar0** [comment]
Dependency management tools have gotten better in the last few years, especially the tools built into Go. People using Go modules have to choose when they want to switch to the v2 series; it won't just switch automatically when they do an update. Maybe now is the time to revisit this.

**Comment by glesica** [comment]
I'm fine with this sort of effort, but this PR is outdated and someone would need to clean it up. I'd also like to address the `go generate` issues first so that a hypothetical v2 could be a little easier to work on... see: https://github.com/stretchr/testify/issues/841.

**Comment by mvdkleijn** [comment]
Since #841 is now closed, from what I can tell this can move forward again. There's issue #399 however, that makes a fair point about the argument order.

**Comment by boyan-soubachov** [comment]
I am closing this PR due to the age of it. I imagine a lot of these changes have been implemented over time? If not and you wish to reopen & rebase onto the latest branch, I'd be happy to review for you :)

**Pull request closed without merging**
