### PR TITLE
Allow mock expectations to be ordered

### LINKED ISSUE #741: assert mock calls in order

### PR DESCRIPTION
**Pull request by brackendawson**
## Summary
Allow mock expectations to be ordered

## Changes
* Give each `Call` to be used in `Mock.ExpectedCalls` a `[]*Call` which must all be satisfied first.
* Define `Call.NotBefore()` to allow the above to be populated.
* Check each call's requirements before processing the found expected call. This needed some existing code to be extracted to a new method `Mock.checkExpectation()`.

## Motivation
People want to check that some calls were made in a necessary order.

```go
call1 := mockThing.On("Init").Return(nil)
call2 := mockThing.On("Do").Return(nil).NotBefore(call1)
mockThing.On("Close").Return(nil).NotBefore(call1, call2)
```

## Related issues
Closes #741

### CODE REVIEW

**Review by boyan-soubachov — DISMISSED** [review]
LGTM, thank you for your contribution :)

**Comment by barp** [comment]
When will this be merged?

**Comment by ehmm** [comment]
Are we missing something to merge this?

**Comment by boyan-soubachov** [comment]
There are conflicts to resolve on `mock/mock.go`. @brackendawson , do you mind giving them a look? :)

**Comment by brackendawson** [comment]
There you go. 🙂

**Review by boyan-soubachov — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
