### PR TITLE
Detect plurality for suffix in Len

### PR DESCRIPTION
**Pull request by mlsteele**
Change this:
`... should have 2 item(s), but has 3`

To this:
`... should have 1 item, but has 3`
`... should have 2 items, but has 3`

### CODE REVIEW

**Comment by philtay** [comment]
This repo has been forked. Please feel free to open a new PR here: https://github.com/test-go/testify

**Comment by mlsteele** [comment]
Thanks @philtay! Glad that's picking up steam. Opened https://github.com/test-go/testify/pull/14

**Comment by Hanzei** [comment]
https://github.com/test-go/testify/pull/14 is merged. Can we close this?

**Comment by mlsteele** [comment]
Sure

**Pull request closed without merging**
