### PR TITLE
Update License file copyright year

### PR DESCRIPTION
**Pull request by AngelKitty**

### CODE REVIEW

**Comment by glesica** [comment]
There are quite a few contributors and AFAIK the project has never had a copyright assignment requirement. Should we add "and contributors" or something to the end of that?

**Comment by AngelKitty** [comment]
@glesica It looks like no bad.

**Comment by glesica** [comment]
Not sure what you mean but that.

**Comment by AngelKitty** [comment]
@glesica I mean that it is more appropriate to remove "and contributors".

**Comment by AngelKitty** [comment]
@glesica But this is the default format, Shall we change it?

**Comment by glesica** [comment]
I'm not saying change the format, just that we should, perhaps, include a reference to the fact that many, many people hold a copyright over some portions of the code, at least as far as I know.

See https://opensource.stackexchange.com/questions/5508/what-does-and-contributors-in-the-copyright-byline-imply for some discussion.

**Comment by mvdkleijn** [comment]
In my humble opinion, the line should read: `Copyright (c) 2012-2020 Mat Ryer, Tyler Bunnell and contributors`

This change would correctly point out the fact that Mat and Tyler are the original authors, but that there are many other contributors that have valid copyright claims on pieces of code.

**Comment by AngelKitty** [comment]
@glesica OK, Could you please review it again?

**Pull request merged**
