### PR TITLE
Add inequality assertions

### PR DESCRIPTION
**Pull request by alexpantyukhin**
Add comparison methods https://github.com/stretchr/testify/issues/710

From the issue:

I have created a test collection comparisons there https://github.com/alexpantyukhin/assertord . I believe many of them are redundant but it's just for demo. Any thoughts could it be good idea to integrate that functionality into the `testify`? Also I guess it would be good to have `assert.IsGreater`, `assert.IsGreaterOrEqual`, `assert.IsLess`, `assert.IsLessOrEqual` in the `testify`.

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
Add comparison methods https://github.com/stretchr/testify/issues/710

**Comment by alexpantyukhin** [comment]
Hi @georgelesica-wf . What's about status of this PR?

**Comment by georgelesica-wf** [comment]
Sorry, I've been busy, hopefully I'll have some time in the next few days.

**Comment by alexpantyukhin** [comment]
@georgelesica-wf okay! :)

**Pull request merged**
