### PR TITLE
Move teardown defers to before setup

### PR DESCRIPTION
**Pull request by AaronNBrock**
A solution proposition for my issue #849

### CODE REVIEW

**Comment by glesica** [comment]
I'm not opposed to this on principle, but I want to give it a few days to percolate in case this has consequences I'm not thinking of.

**Comment by dmarkhas** [comment]
+1 for this, we're also hitting the same issue and would love to see this get fixed

**Comment by AaronNBrock** [comment]
The only case I can see where this would cause a test to break is if they relied on the fact that the tear down doesn't run if the SetUp fails, e.g. SetUp creates a file & tear down tries to read it w/o verifying it exists.

But, that's probably bad practice anyhow.

**Comment by boyan-soubachov** [comment]
> The only case I can see where this would cause a test to break is if they relied on the fact that the tear down doesn't run if the SetUp fails, e.g. SetUp creates a file & tear down tries to read it w/o verifying it exists.
> 
> But, that's probably bad practice anyhow.

👍 . Hopefully not too many people rely on this behaviour.

**Comment by boyan-soubachov** [comment]
image
Oddly, the branch still has merge conflicts. Do you mind doing a rebase and force-push?

**Comment by boyan-soubachov** [comment]
Have rebased in a separate PR (#931) due to demand and time.

**Comment by mvdkleijn** [comment]
Closing this PR in favor of the new one at #931

**Pull request closed without merging**
