### PR TITLE
ElementsMatch array/slice assertion ignoring order

### PR DESCRIPTION
**Pull request by emou**
An assertion that compares the elements of the slices/arrays disregarding the order,
i.e. it checks whether each element in the first slice/array appears the same number of times in it
as in the second slice/array.

This name seemed like it would be easy to find.

Possible alternatives for the name:
- ContainsSameElements
- IsPermutation (C++: http://en.cppreference.com/w/cpp/algorithm/is_permutation)
- MatchArray (rspec: http://www.rubydoc.info/github/rspec/rspec-expectations/RSpec/Matchers:match_array)
- EqualSorted
- Other ideas?

This implementaiton is O(N^2), while sorting both lists first would be O(nlogn).
However, this one doesn't need to copy both lists and sort them (which would be more complicated code). Also, it uses less memory (N bytes of memory instead of 8 x N).

I realize this was deemed as out of scope
https://github.com/stretchr/testify/issues/275
but I decided to give it a shot as I needed it also.

### CODE REVIEW

**Comment by adamwg** [comment]
I would use this if merged. That said, you can emulate it by checking that two lists are subsets of one another:

```go
assert.Subset(t, a, b)
assert.Subset(t, b, a)
```

**Comment by asko** [comment]
Is there progress on this?

**Comment by philtay** [comment]
This repo has been forked. Please feel free to open a new PR here: https://github.com/test-go/testify

**Comment by ernesto-jimenez** [comment]
Thanks @emou, merging.

**Pull request merged**
