### PR TITLE
indent actual value for better comparison with expected value

### PR DESCRIPTION
**Pull request by Oppodelldog**
I found an indentation of the actual value quite useful for comparison.
My usecase for this change was the equal assertion on two urls with parameters where a parameter was missing in one of both urls.
An indentation helped a lot in this case.

### CODE REVIEW

**Comment by philtay** [comment]
This repo has been forked. Please feel free to open a new PR here: https://github.com/test-go/testify

**Comment by Oppodelldog** [comment]
@philtay, I guess your fork will be updated when this Pr gets merged.
Is there something wrong with this PR? I created it from my fork against stretchr:master.

**Comment by philtay** [comment]
@Oppodelldog nothing wrong. The fact is that this repo is not maintained anymore. Most probably your PR will never be merged here. You created it 5 months ago...

**Comment by ernesto-jimenez** [comment]
@Oppodelldog thanks, merging

@philtay, it's not abandoned, it just takes quite a bit of time to review things properly and I've been quite busy with the new job.

More than happy to get help triaging and reviewing issues and PRs :)

**Comment by philtay** [comment]
@ernesto-jimenez c'mon...

**Pull request merged**
