### PR TITLE
fail: add test name for failing log

### PR DESCRIPTION
**Pull request by posener**

### CODE REVIEW

**Comment by posener** [comment]
Test fail on something that seems unrelated to the change:
```
go tool: no such tool "vet"; to install:
	go get golang.org/x/tools/cmd/vet
```

**Comment by posener** [comment]
Hi, I got no response for a long time.
I really think this is useful when debugging failing tests.

**Comment by philtay** [comment]
This repo has been forked. Please feel free to open a new PR here: https://github.com/test-go/testify

**Comment by ernesto-jimenez** [comment]
@posener closing in favour of https://github.com/stretchr/testify/pull/533, which has the clean history (you will still appear as the commit author).

Will merge once CI runs.

Thanks

**Pull request closed without merging**
