### PR TITLE
README: fix install command

### PR DESCRIPTION
**Pull request by sonofgibs**
`go get` resulted in undefined errors on my machine. Once I updated my Go version to 1.19 I got this handy message:
'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'

So updated the documentation to match. :smile:

## Summary

Updated installation guidelines

## Changes

Updated installation guidelines to adhere to Go 1.19 go get deprecation

## Motivation

Simple but annoying to google, easy to fix

go install github.com/stretchr/testify@latest

### CODE REVIEW

**Review by lisitsky — APPROVED** [review]

**Review by dolmen — CHANGES_REQUESTED** [review]
At this point we must just drop the GOPATH-mode version and show only the Go Modules one (`go install`).

**Comment by sonofgibs** [comment]
> drop the GOPATH-mode version and show only the Go Modules

PR has been updated, please re-review

**Comment by dolmen** [comment]
The "Staying up-to-date" section must be updated as well.

**Review by dolmen — CHANGES_REQUESTED** [review]
The 'Staying up-to-date' section must be fixed as well.

**Pull request closed without merging**
