### PR TITLE
comments for the require package

### PR DESCRIPTION
**Pull request by parth-p-shah**
## Summary
What was asked and done in #1610 , with the review comments addressed.

## Changes
Added a "replace" function to the template
require.go.tmpl now replaces the package name accordingly
require.go.tmpl now adds another line to the function-docs explaining the difference to the assert-function

## Motivation
In case of test-cases using both require and assert it gets confusing because the function docs for the require package are referencing the assert package and don't really document the actual function.
## Related issues
#1610 - Generate better comments for require package

### CODE REVIEW

**Comment by brackendawson** [comment]
Can you base this on @Neokil's work? Ie begin with their branch and add a commit taking the other parts out. You also need to run `go generate ./...`.

**Comment by parth-p-shah** [comment]
> Can you base this on @Neokil's work? Ie begin with their branch and add a commit taking the other parts out. You also need to run `go generate ./...`.

I'm not able to push into his branch. Also go generate ./... is adding the line:
// Failure of this check is fatal ([testing.T.FailNow] is called on failure).
under every function.

**Comment by brackendawson** [comment]
You don't need to push to their branch:
```sh
git remote add Neokil git@github.com:Neokil/testify.git
git fetch Neokil
git checkout generate-better-comments-for-require-package
# do work
# commit 
# push to your fork
# open PR
```

This keeps the correct attribution on the work. You'll need to have go generate working and CI passing before this can be reviewed.

**Comment by brackendawson** [comment]
Thank you for your efforts @parth-p-shah, but the author has responded in #1610 now.

**Pull request closed without merging**
